models:
  gpt4:
    api_name: "openai/gpt-4"
    
  gpt4o:
    api_name: "openai/gpt-4o"
    
  gpt4o_mini:
    api_name: "openai/gpt-4o-mini"

  gemini_2.0_pro_exp_02_05:
    api_name: "google/gemini-2.0-pro-exp-02-05:free"

  deepseek_r1:
    api_name: "deepseek/deepseek-r1"

  gemini_2.0_flash:
    api_name: "google/gemini-2.0-flash-001"
  
  gemini_2.0_flash_thinking:
    api_name: "google/gemini-2.0-flash-thinking-exp:free"

  llama3.3-70b-instruct:
    api_name: "meta-llama/llama-3.3-70b-instruct" 

  

  # claude_sonnet:
  #   api_name: "anthropic/claude-3-sonnet"
    
  # gemini_pro:
  #   api_name: "google/gemini-1.5-pro"

  # gemini_flash:
  #   api_name: "google/gemini-1.5-flash"
    
  # llama3_8b:
  #   api_name: "meta-llama/llama-3-8b"
